use pjsekai_scores_rs::line::{Line, LineType, ParsedItem};
use pjsekai_scores_rs::notes::directional::{Directional, DirectionalType};
use pjsekai_scores_rs::notes::slide::Slide;
use pjsekai_scores_rs::notes::tap::{Tap, TapType};
use pjsekai_scores_rs::notes::{NO_NOTE, NoteBase, NoteData};
use pjsekai_scores_rs::{Drawing, Fraction, Lyric, MusicMeta, Rebase, Score};

fn rich_sus() -> &'static str {
    r##"
#TITLE "Coverage & <Test>"
#SUBTITLE "Integration"
#ARTIST "Haruki"
#GENRE "Rhythm"
#DESIGNER "Codex"
#DIFFICULTY 3
#PLAYLEVEL 30
#JACKET "jacket&cover.png"
#BASEBPM 120
#MOVIEOFFSET 1/2
#REQUEST "ticks_per_beat 480"
#HISPEED 01
#NOSPEED 0
#TIL01: "0'0:1.0,1'240:1.5,3'0:0.75"
#BPM01: 120
#BPM02: 180
#00008: 01
#00108: 02
#00202: 3
#00032A: 14
#00012: 24
#00134A: 34
#00154: 34
#00236A: 24
#00216: 54
#00256: 44
#00093B: 12
#00195B: 32
#00297B: 22
#00312: 1121314151617181
#00452: 112131415161
#00110: 11
#00211: 11
#0031E: 21
"##
}

#[test]
fn rich_sus_workflow_renders_chart_features() {
    let mut score = Score::parse(rich_sus());
    assert_eq!(score.meta.title.as_deref(), Some("Coverage & <Test>"));
    assert_eq!(score.meta.movieoffset, Some(0.5));
    assert!(score.active_notes.len() >= 10);
    assert!(score.events.iter().any(|event| event.speed == Some(1.5)));
    assert!(
        score
            .events
            .iter()
            .any(|event| event.text.as_deref() == Some("SKILL"))
    );
    assert!(
        score
            .events
            .iter()
            .any(|event| event.text.as_deref() == Some("SUPER FEVER!!"))
    );

    let lyric = Lyric::load("0: Hello//世界\n1: A/B/C\ninvalid\n");
    assert_eq!(lyric.words.len(), 5);
    assert_eq!(lyric.words[1].bar, Fraction::new(2, 3));

    let music_meta = MusicMeta {
        fever_end_time: 10.0,
        fever_score: 0.2,
        skill_score_solo: vec![0.1],
        skill_score_multi: vec![0.15],
    };
    let mut drawing = Drawing::new(
        Some("https://assets.example.test/notes".to_string()),
        Some(".custom { opacity: 0.5; }".to_string()),
        true,
        Some(music_meta),
        None,
        Some("Coverage Test".to_string()),
    );
    drawing.set_note_asset_extension(" .WEBP ");
    drawing.set_font_paths(["font-a.otf", "", "font-b.ttf"]);
    drawing.add_font_path("font-c.ttc");
    drawing.add_font_path("  ");
    drawing.set_font_dirs(["fonts/a", "", "fonts/b"]);
    drawing.add_font_dir("fonts/c");
    drawing.add_font_dir("");

    let svg = drawing.svg(&mut score, Some(&lyric));
    assert!(svg.starts_with("<svg"));
    assert!(svg.ends_with("</svg>"));
    assert!(svg.contains("Coverage &amp; &lt;Test&gt; - Haruki"));
    assert!(svg.contains("Generated by Coverage Test"));
    assert!(svg.contains("notes_0.webp"));
    assert!(svg.contains("class=\"lyric-text\""));
    assert!(svg.contains("class=\"skill-duration\""));
    assert!(svg.contains("class=\"fever-duration\""));
    assert!(svg.contains("notes_flick_arrow"));
    assert!(!drawing.special_cover_objects.is_empty());
    assert_eq!(drawing.config.font_paths.len(), 3);
    assert_eq!(drawing.config.font_dirs.len(), 3);

    drawing.set_style_sheet(Some(".second { fill: red; }".to_string()));
    assert!(drawing.style_sheet.contains(".second"));
}

#[test]
fn rebase_covers_linked_notes_events_and_timing() {
    let mut source = Score::parse(rich_sus());
    let rebase = Rebase::from_json(
        r#"{
            "offset": -0.25,
            "meta": {
                "title": "Rebased title",
                "background": "rebased-background.png",
                "basebpm": 150,
                "movieoffset": 0.75,
                "ignored": true
            },
            "events": [
                {
                    "bar": 0.0,
                    "bpm": 150.0,
                    "barLength": 4.0,
                    "sentenceLength": 2,
                    "section": "Intro",
                    "text": "Start"
                },
                {
                    "bar": 2.0,
                    "bpm": 200.0,
                    "barLength": 3.0,
                    "sentenceLength": 3,
                    "section": "Verse",
                    "text": "Shift"
                }
            ]
        }"#,
    )
    .expect("valid rebase JSON");

    assert_eq!(rebase.offset, -0.25);
    assert_eq!(rebase.events.len(), 2);
    assert_eq!(rebase.meta.basebpm, Some(150.0));

    let mut rebased = rebase.apply(&mut source);
    assert_eq!(rebased.meta.title.as_deref(), Some("Coverage & <Test>"));
    assert_eq!(
        rebased.meta.background.as_deref(),
        Some("rebased-background.png")
    );
    assert!(!rebased.active_notes.is_empty());
    assert!(rebased.events.iter().any(|event| event.speed.is_some()));
    assert!(rebased.events.iter().any(|event| event.section.is_some()));
    assert!(rebased.events.iter().any(|event| event.text.is_some()));

    let start = rebased.get_time(Fraction::zero());
    let later = rebased.get_time(Fraction::from_integer(3));
    assert!(later > start);
    assert!(rebased.get_time_delta_f64(Fraction::zero(), Fraction::one()) > 0.0);
    let event = rebased.get_event(Fraction::from_integer(2));
    assert_eq!(event.section.as_deref(), Some("Verse"));
    let one_bar_time = rebased.get_time_f64(Fraction::one());
    let recovered_bar = rebased.get_bar_by_time(one_bar_time);
    assert!((recovered_bar.to_f64() - 1.0).abs() < 1e-6);

    let mut drawing = Drawing::new(None, None, false, None, None, None);
    let svg = drawing.svg(&mut rebased, None);
    assert!(svg.contains("Rebased title") || svg.contains("Coverage &amp; &lt;Test&gt;"));
    assert!(svg.contains("Intro") || svg.contains("Verse"));
}

#[test]
fn line_parser_handles_all_supported_line_families() {
    let comment = Line::new("// comment");
    assert_eq!(comment.line_type, LineType::Comment);
    assert!(comment.parse().is_empty());

    let meta = Line::new("#TITLE 'Quoted title'").parse();
    assert!(matches!(meta.as_slice(), [ParsedItem::Meta(_)]));

    let request = Line::new("#REQUEST \"ticks_per_beat 960\"").parse();
    assert!(matches!(
        request.as_slice(),
        [ParsedItem::TicksPerBeat(value)] if value.0 == 960
    ));

    let speed = Line::new("#TIL0A: \"2'10:0.5,1'20:2.0\"").parse();
    let ParsedItem::SpeedDefinition(speed) = &speed[0] else {
        panic!("expected speed definition");
    };
    assert_eq!(speed.id, 10);
    assert_eq!(speed.items[0].bar, 1);
    assert_eq!(speed.items[1].speed, 0.5);

    assert_eq!(Line::new("#00008: 0102").parse().len(), 2);
    assert_eq!(Line::new("#00012: 1121").parse().len(), 2);
    assert_eq!(Line::new("#00032A: 1121").parse().len(), 2);
    assert_eq!(Line::new("#00052: 1121").parse().len(), 2);
    assert_eq!(Line::new("#00092A: 1121").parse().len(), 2);
    assert!(Line::new("#BPMZZ: invalid").parse().is_empty());
    assert!(Line::new("#UNKNOWN value").parse().is_empty());
}

#[test]
fn note_classification_covers_linked_attachment_states() {
    let critical = NoteData::Tap(
        NoteBase::new(Fraction::zero(), 2, 1, TapType::Critical as i32),
        Tap,
    );
    let trend = NoteData::Tap(
        NoteBase::new(Fraction::zero(), 3, 1, TapType::Trend as i32),
        Tap,
    );
    let cancel = NoteData::Tap(
        NoteBase::new(Fraction::zero(), 4, 1, TapType::Cancel as i32),
        Tap,
    );
    let mut directional = Directional::new();
    directional.tap_idx = 0;
    let directional = NoteData::Directional(
        NoteBase::new(Fraction::zero(), 2, 1, DirectionalType::UpperRight as i32),
        directional,
    );
    let mut slide = Slide::new(1, false);
    slide.tap_idx = 1;
    slide.directional_idx = 3;
    slide.head_idx = 4;
    let slide = NoteData::Slide(NoteBase::new(Fraction::zero(), 2, 1, 3), slide);
    let arena = vec![critical, trend, cancel, directional, slide];

    assert!(arena[0].is_critical(&arena));
    assert!(arena[1].is_trend(&arena));
    assert!(arena[2].is_none(&arena));
    assert!(arena[3].is_critical(&arena));
    assert_eq!(arena[4].is_tick(&arena), Some(false));

    let mut decoration = Slide::new(2, true);
    assert_eq!(decoration.is_tick(&arena, 1), None);
    decoration.tap_idx = 2;
    assert_eq!(decoration.is_tick(&arena, 1), None);
    decoration.tap_idx = 1;
    assert_eq!(decoration.is_tick(&arena, 1), Some(false));
    decoration.tap_idx = 0;
    assert_eq!(decoration.is_tick(&arena, 1), Some(true));

    let plain = Slide::new(3, false);
    assert!(!plain.is_path(0));
    assert!(plain.is_path(3));
    assert_eq!(plain.is_tick(&arena, 5), None);
    assert_eq!(plain.is_tick(&arena, 3), Some(false));
    assert_eq!(TapType::from_i32(99), None);
    assert_eq!(DirectionalType::from_i32(99), None);
    assert_eq!(NO_NOTE, usize::MAX);
}

#[test]
fn score_auto_detection_and_empty_timeline_are_stable() {
    let mut empty = Score::new();
    assert_eq!(empty.timed_events().len(), 1);
    assert_eq!(empty.get_time(Fraction::new(1, 2)), Fraction::one());
    assert_eq!(empty.get_event(Fraction::zero()).sentence_length, Some(4));

    let sus =
        Score::parse_auto("#TITLE Auto\n#BPM01: 120\n#00008: 01\n").expect("SUS auto-detection");
    assert_eq!(sus.meta.title.as_deref(), Some("Auto"));

    let parsed: Score = "#TITLE Trait".parse().expect("infallible FromStr");
    assert_eq!(parsed.meta.title.as_deref(), Some("Trait"));
    assert!(Score::parse_auto("{not valid json}").is_err());
}
